### ISSUE TITLE
Are There Redundant Calculations?

### ISSUE THREAD

**Issue by KylinC** [czg1225/AsyncDiff#10]
Hi authors,

Thank you for your fascinating paper. However, I have a question regarding the diffusion process as illustrated in Figure 3.
<img width="750" alt="截屏2024-12-05 09 56 06" src="https://github.com/user-attachments/assets/d8c5a1ba-98d1-4ce6-aeed-6117d62926cb">

From the image and the paper, I believe that the computations outside the red box are redundant. If we know in advance how many steps we need, for example, if our final target is x_{T-5}, then are the calculations outside the red box still necessary?

Thank you for your clarification.

**Comment by czg1225** [comment]
Hi @KylinC ,
Thanks for your interest. In fact, the denoising model outputs the predicted noise $n_{T}$ at each timestep $T$, but not the latent feature $x_{T}$. We simplify this step in the figure.  If we want to get $x_{T-5}$ we must get $x_{T-4}$ and $n_{T-4}$, because $x_{T-5}=x_{T-4}-n_{T-4}$. As a result, the computations outside the red box **are not redundant**.

**Comment by KylinC** [comment]
Thx!
